# 01 NumPy Exercises 
#### (by Jose Portila)

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### 1. Import NumPy as np

In [2]:
import numpy as np
np

<module 'numpy' from 'C:\\Users\\Entwan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy\\__init__.py'>

#### 2. Create an array of 10 zeros 

In [5]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [6]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [15]:
c = np.full((1,10),5)
c = np.ones(10)*5
c

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Create an array of the integers from 10 to 50

In [18]:
a = np.arange(10,51)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Create an array of all the even integers from 10 to 50

In [30]:
a = np.arange(10,51,2)
x = np.array([x for x in range(10,51) if x %2 ==0])
x
a


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [36]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Create a 3x3 identity matrix

In [39]:
a = np.arange(9.).reshape(3,3)
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

#### 9. Use NumPy to generate a random number between 0 and 1

In [41]:
a = np.random.random(1)
a

array([0.82386457])

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [43]:
a = np.random.normal(0,1,25)
a

array([-0.69422283, -0.86060948, -0.91223465,  0.14889411,  0.37305904,
       -0.04973275, -1.70873186, -0.64675866, -0.88316429,  1.28804676,
        1.4249621 ,  1.90825468, -0.60565723, -0.73026718, -1.37868112,
       -1.04564203,  1.38716669,  0.99886906,  0.3925952 , -1.21194603,
       -0.47802621, -0.86186383,  1.28983909,  0.63453275,  0.58910551])

#### 11. Create the following matrix:

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [9]:

#z = np.array([])
#x = 0.11
#y = 0.2
#a = np.linspace(0.01, 0.1, 10)

#while y < 1:
#    z = np.linspace(x, y, 10)
#    z = np.vstack([a, z])
#    x += 0.01
#    y += 0.1

#print(z)
    
matrix = np.linspace(0.01, 1.0, 100).reshape(10, 10)
print(matrix)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### 12. Create an array of 20 linearly spaced points between 0 and 1:

In [11]:
a = np.linspace(0.1,1,20)
a

array([0.1       , 0.14736842, 0.19473684, 0.24210526, 0.28947368,
       0.33684211, 0.38421053, 0.43157895, 0.47894737, 0.52631579,
       0.57368421, 0.62105263, 0.66842105, 0.71578947, 0.76315789,
       0.81052632, 0.85789474, 0.90526316, 0.95263158, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code to produce the following output (from referrring to mat): 

``` 
array([[12, 13, 14, 15],  
       [17, 18, 19, 20],  
       [22, 23, 24, 25]])
```

In [19]:
mat[2:5,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Write code below to produce the following output (from referring to mat): 
``` 20 ```

In [22]:
mat[3,4]

20

#### 15. Write code below to produce the following output (from referring to mat):
  
```
array([[ 2],
       [ 7],
       [12]])
```

In [34]:
mat[:3,1,].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

#### 16. Write code that produces the following output (from referring to mat)

``` array([21, 22, 23, 24, 25])```

In [35]:
mat[4,0:]

array([21, 22, 23, 24, 25])

#### 17. Write code that produces the following output (from referring to mat)

```
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [37]:
mat[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### 18. Get the sum of all the values in mat

In [39]:
mat.sum()

325

#### 19. Get the standard deviation of the values in mat

In [40]:
np.std(mat)

7.211102550927978

#### 20. Get the sum of all the columns in mat

In [47]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [49]:
#Create a vector as a Row
vector_row = np.array([ 1,2,3,4,5,6 ])

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Select 3rd element of Vector
print(vector_row[2])

#Select 2nd row 2nd column
print(matrix[1,1])
#Select all elements of a vector
print(vector_row[:])
#Select everything up to and including the 3rd element
print(vector_row[:3])
#Select the everything after the 3rd element
print(vector_row[3:])
#Select the last element
print(vector_row[-1])
#Select the first 2 rows and all the columns of the matrix
print(matrix[:2,:])
#Select all rows and the 2nd column of the matrix
print(matrix[:,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
5
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


In [50]:
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
#View the Number of Rows and Columns
print(matrix.shape)
#View the number of elements (rows*columns)
print(matrix.size)
#View the number of Dimensions(2 in this case)
print(matrix.ndim)

(3, 3)
9
2


You want to apply some function to multiple elements in an array.

Numpy’s vectorize class converts a function into a function that can apply to multiple elements in an array or slice of an array.

In [51]:
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Create a function that adds 100 to something
add_100 =lambda i: i+100

#Convert it into a vectorized function
vectorized_add_100= np.vectorize(add_100)

#Apply function to all elements in matrix
print(vectorized_add_100(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[101 102 103]
 [104 105 106]
 [107 108 109]]
